Bump required version of gnome-settings-daemon to 3.8
Reported by Pacho Ramos in https://bugzilla.gnome.org/697146
and from the references gentoo bug report:

With gnome-base/gnome-settings-daemon-3.6.4:

gdusdmanager.c: At top level:
gdusdmanager.c:42:1: error: unknown type name 'GduSdClass'
gdusdmanager.c:80:1: warning: 'gdu_sd_manager_start' defined but not used [-Wunused-function]
gdusdmanager.c:124:1: warning: 'gdu_sd_manager_new' defined but not used [-Wunused-function]
make[3]: *** [libgdu_sd_la-gdusdmanager.lo] Error 1